In [53]:
#1. Import the NUMPY package under the name np.
import numpy as np


#2. Print the NUMPY version and the configuration.



#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2,3,5))

#4. Print a.
print(a)

[[[0.53501105 0.86451789 0.58123437 0.81359526 0.9676912 ]
  [0.13723113 0.1985766  0.04542361 0.13189318 0.30464957]
  [0.75504479 0.03909661 0.84397373 0.16311499 0.47547593]]

 [[0.66169718 0.39871391 0.06536348 0.45789519 0.58826749]
  [0.31769186 0.71016167 0.52773322 0.67486391 0.89646358]
  [0.74690743 0.69518159 0.02239032 0.15304138 0.32635141]]]


In [54]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.random.random((5,2,3))
print(b)

#7. Do a and b have the same size? How do you prove that in Python code?

if a.size == b.size:
    print(True)

print(a.size)
print(b.size)

[[[0.79335271 0.25530433 0.16782428]
  [0.51804046 0.55492018 0.17596474]]

 [[0.96507083 0.78442671 0.94385437]
  [0.80482596 0.0961426  0.84163862]]

 [[0.65620123 0.88595378 0.90876579]
  [0.76122036 0.31528702 0.59812498]]

 [[0.32760764 0.43047496 0.19494597]
  [0.19339505 0.56071353 0.23107232]]

 [[0.93674148 0.03413515 0.49281718]
  [0.63118339 0.75296632 0.94048132]]]
True
30
30


In [8]:
#8. Are you able to add a and b? Why or why not?
a+b
#Not possible to sum arrays with different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [55]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
#5,2,3:
print(b)
print(b.shape)

#2,3,5:
c = b.transpose([1,2,0])
print(c)
print(c.shape)

#3,2,5
d = (b.T)
print(d)
print(d.shape)


[[[0.79335271 0.25530433 0.16782428]
  [0.51804046 0.55492018 0.17596474]]

 [[0.96507083 0.78442671 0.94385437]
  [0.80482596 0.0961426  0.84163862]]

 [[0.65620123 0.88595378 0.90876579]
  [0.76122036 0.31528702 0.59812498]]

 [[0.32760764 0.43047496 0.19494597]
  [0.19339505 0.56071353 0.23107232]]

 [[0.93674148 0.03413515 0.49281718]
  [0.63118339 0.75296632 0.94048132]]]
(5, 2, 3)
[[[0.79335271 0.96507083 0.65620123 0.32760764 0.93674148]
  [0.25530433 0.78442671 0.88595378 0.43047496 0.03413515]
  [0.16782428 0.94385437 0.90876579 0.19494597 0.49281718]]

 [[0.51804046 0.80482596 0.76122036 0.19339505 0.63118339]
  [0.55492018 0.0961426  0.31528702 0.56071353 0.75296632]
  [0.17596474 0.84163862 0.59812498 0.23107232 0.94048132]]]
(2, 3, 5)
[[[0.79335271 0.96507083 0.65620123 0.32760764 0.93674148]
  [0.51804046 0.80482596 0.76122036 0.19339505 0.63118339]]

 [[0.25530433 0.78442671 0.88595378 0.43047496 0.03413515]
  [0.55492018 0.0961426  0.31528702 0.56071353 0.75296632]]

 [

In [65]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
print("a",a)
print("c",c)

if a.shape==c.shape:
    print(True)
    
d=a+c
print("d",d)

# Other formula
x=np.add(a,c)
print("x",x)



a [[[0.53501105 0.86451789 0.58123437 0.81359526 0.9676912 ]
  [0.13723113 0.1985766  0.04542361 0.13189318 0.30464957]
  [0.75504479 0.03909661 0.84397373 0.16311499 0.47547593]]

 [[0.66169718 0.39871391 0.06536348 0.45789519 0.58826749]
  [0.31769186 0.71016167 0.52773322 0.67486391 0.89646358]
  [0.74690743 0.69518159 0.02239032 0.15304138 0.32635141]]]
c [[[0.79335271 0.96507083 0.65620123 0.32760764 0.93674148]
  [0.25530433 0.78442671 0.88595378 0.43047496 0.03413515]
  [0.16782428 0.94385437 0.90876579 0.19494597 0.49281718]]

 [[0.51804046 0.80482596 0.76122036 0.19339505 0.63118339]
  [0.55492018 0.0961426  0.31528702 0.56071353 0.75296632]
  [0.17596474 0.84163862 0.59812498 0.23107232 0.94048132]]]
True
d [[[1.32836377 1.82958872 1.2374356  1.1412029  1.90443268]
  [0.39253545 0.98300331 0.93137738 0.56236813 0.33878473]
  [0.92286907 0.98295098 1.75273952 0.35806096 0.96829311]]

 [[1.17973764 1.20353987 0.82658384 0.65129024 1.21945088]
  [0.87261205 0.80630427 0.84302024

In [57]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print

print("a",a)
print("d",d)


a [[[0.53501105 0.86451789 0.58123437 0.81359526 0.9676912 ]
  [0.13723113 0.1985766  0.04542361 0.13189318 0.30464957]
  [0.75504479 0.03909661 0.84397373 0.16311499 0.47547593]]

 [[0.66169718 0.39871391 0.06536348 0.45789519 0.58826749]
  [0.31769186 0.71016167 0.52773322 0.67486391 0.89646358]
  [0.74690743 0.69518159 0.02239032 0.15304138 0.32635141]]]
d [[[1.32836377 1.82958872 1.2374356  1.1412029  1.90443268]
  [0.39253545 0.98300331 0.93137738 0.56236813 0.33878473]
  [0.92286907 0.98295098 1.75273952 0.35806096 0.96829311]]

 [[1.17973764 1.20353987 0.82658384 0.65129024 1.21945088]
  [0.87261205 0.80630427 0.84302024 1.23557744 1.6494299 ]
  [0.92287217 1.53682021 0.62051531 0.3841137  1.26683272]]]


In [69]:
#12. Multiply a and c. Assign the result to e.

e=a*c
print("e",e)

# Other formula
y=np.multiply(a,c)
print("y",y)

e [[[0.42445247 0.83432099 0.38140671 0.26654002 0.90647649]
  [0.0350357  0.15576879 0.04024322 0.05677671 0.01039926]
  [0.12671485 0.03690151 0.76697445 0.03179861 0.23432271]]

 [[0.34278591 0.3208953  0.04975601 0.08855466 0.37130467]
  [0.17629363 0.06827679 0.16638743 0.37840533 0.67500689]
  [0.13142937 0.58509167 0.01339221 0.03536363 0.3069274 ]]]
y [[[0.42445247 0.83432099 0.38140671 0.26654002 0.90647649]
  [0.0350357  0.15576879 0.04024322 0.05677671 0.01039926]
  [0.12671485 0.03690151 0.76697445 0.03179861 0.23432271]]

 [[0.34278591 0.3208953  0.04975601 0.08855466 0.37130467]
  [0.17629363 0.06827679 0.16638743 0.37840533 0.67500689]
  [0.13142937 0.58509167 0.01339221 0.03536363 0.3069274 ]]]


In [71]:
#13. Does e equal to a? Why or why not?
print("a",a)
print("e",e)

a [[[0.53501105 0.86451789 0.58123437 0.81359526 0.9676912 ]
  [0.13723113 0.1985766  0.04542361 0.13189318 0.30464957]
  [0.75504479 0.03909661 0.84397373 0.16311499 0.47547593]]

 [[0.66169718 0.39871391 0.06536348 0.45789519 0.58826749]
  [0.31769186 0.71016167 0.52773322 0.67486391 0.89646358]
  [0.74690743 0.69518159 0.02239032 0.15304138 0.32635141]]]
e [[[0.42445247 0.83432099 0.38140671 0.26654002 0.90647649]
  [0.0350357  0.15576879 0.04024322 0.05677671 0.01039926]
  [0.12671485 0.03690151 0.76697445 0.03179861 0.23432271]]

 [[0.34278591 0.3208953  0.04975601 0.08855466 0.37130467]
  [0.17629363 0.06827679 0.16638743 0.37840533 0.67500689]
  [0.13142937 0.58509167 0.01339221 0.03536363 0.3069274 ]]]


In [101]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
print("d",d)
d_min=np.amin(d)
d_max=np.amax(d)
d_mean=np.mean(d)
print(d_min)
print(d_max)
print(d_mean)

d [[[1.32836377 1.82958872 1.2374356  1.1412029  1.90443268]
  [0.39253545 0.98300331 0.93137738 0.56236813 0.33878473]
  [0.92286907 0.98295098 1.75273952 0.35806096 0.96829311]]

 [[1.17973764 1.20353987 0.82658384 0.65129024 1.21945088]
  [0.87261205 0.80630427 0.84302024 1.23557744 1.6494299 ]
  [0.92287217 1.53682021 0.62051531 0.3841137  1.26683272]]]
0.3387847269920874
1.9044326812465924
1.0284235597106064


In [92]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f=np.empty([2,3,5])
print(f)

[[[1.32836377 1.82958872 1.2374356  1.1412029  1.90443268]
  [0.39253545 0.98300331 0.93137738 0.56236813 0.33878473]
  [0.92286907 0.98295098 1.75273952 0.35806096 0.96829311]]

 [[1.17973764 1.20353987 0.82658384 0.65129024 1.21945088]
  [0.87261205 0.80630427 0.84302024 1.23557744 1.6494299 ]
  [0.92287217 1.53682021 0.62051531 0.3841137  1.26683272]]]


In [102]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
# If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
# If a value equals to d_mean, assign 50 to the corresponding value in f.
# Assign 0 to the corresponding value(s) in f for d_min in d.
# Assign 100 to the corresponding value(s) in f for d_max in d.
# In the end, f should have only the following values: 0, 25, 50, 75, and 100.
# Note: you dont have to use Numpy in this question.

print("d",d)

for i in range(2):
    for j in range(3):
        for k in range(5):
            if d_mean < d[i][j][k] < d_max:
                f[i][j][k]=75
            elif d_min < d[i][j][k] < d_mean:
                f[i][j][k]=25
            elif d[i][j][k] == d_mean:
                f[i][j][k]=50
            elif d[i][j][k] == d_min:
                f[i][j][k]=0
            elif d[i][j][k] == d_max:
                f[i][j][k]=100
print("f",f)
print("min",d_min)
print("max",d_max)
print("mean",d_mean)
                

d [[[1.32836377 1.82958872 1.2374356  1.1412029  1.90443268]
  [0.39253545 0.98300331 0.93137738 0.56236813 0.33878473]
  [0.92286907 0.98295098 1.75273952 0.35806096 0.96829311]]

 [[1.17973764 1.20353987 0.82658384 0.65129024 1.21945088]
  [0.87261205 0.80630427 0.84302024 1.23557744 1.6494299 ]
  [0.92287217 1.53682021 0.62051531 0.3841137  1.26683272]]]
f [[[ 75.  75.  75.  75. 100.]
  [ 25.  25.  25.  25.   0.]
  [ 25.  25.  75.  25.  25.]]

 [[ 75.  75.  25.  25.  75.]
  [ 25.  25.  25.  75.  75.]
  [ 25.  75.  25.  25.  75.]]]
min 0.3387847269920874
max 1.9044326812465924
mean 1.0284235597106064


In [ ]:
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

In [108]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
# ("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
# array([[[ 'D',  'D',  'D',  'B',  'D'],
#         [ 'D',  'D',  'B',  'B',  'B'],
#         [ 'D',  'B',  'D',  'D',  'D']],

#        [[ 'B',  'B',  'B',  'B',  'E'],
#         [ 'D',  'D',  'D',  'D',  'D'],
#         [ 'B',  'D',   'A',  'D', 'D']]])
# Again, you don't need Numpy in this question.

print("d",d)

w=str(f)
print(w)
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d_mean < d[i][j][k] < d_max:
                w[i][j][k]="D"
            elif d_min < d[i][j][k] < d_mean:
                w[i][j][k]="B"
            elif d[i][j][k] == d_mean:
                w[i][j][k]="C"
            elif d[i][j][k] == d_min:
                w[i][j][k]="A"
            elif d[i][j][k] == d_max:
                w[i][j][k]="E"
print("w",w)
print("min",d_min)
print("max",d_max)
print("mean",d_mean)

d [[[1.32836377 1.82958872 1.2374356  1.1412029  1.90443268]
  [0.39253545 0.98300331 0.93137738 0.56236813 0.33878473]
  [0.92286907 0.98295098 1.75273952 0.35806096 0.96829311]]

 [[1.17973764 1.20353987 0.82658384 0.65129024 1.21945088]
  [0.87261205 0.80630427 0.84302024 1.23557744 1.6494299 ]
  [0.92287217 1.53682021 0.62051531 0.3841137  1.26683272]]]
[[[ 75.  75.  75.  75. 100.]
  [ 25.  25.  25.  25.   0.]
  [ 25.  25.  75.  25.  25.]]

 [[ 75.  75.  25.  25.  75.]
  [ 25.  25.  25.  75.  75.]
  [ 25.  75.  25.  25.  75.]]]


AttributeError: 'str' object has no attribute 'append'